package com.yt.daydaystudy.demo_greendao.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yt.daydaystudy.demo_greendao.dao.Nan;
import com.yt.daydaystudy.demo_greendao.dao.Nv;
import com.yt.daydaystudy.demo_greendao.dao.User;

import com.yt.daydaystudy.demo_greendao.greendao.NanDao;
import com.yt.daydaystudy.demo_greendao.greendao.NvDao;
import com.yt.daydaystudy.demo_greendao.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig nanDaoConfig;
    private final DaoConfig nvDaoConfig;
    private final DaoConfig userDaoConfig;

    private final NanDao nanDao;
    private final NvDao nvDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        nanDaoConfig = daoConfigMap.get(NanDao.class).clone();
        nanDaoConfig.initIdentityScope(type);

        nvDaoConfig = daoConfigMap.get(NvDao.class).clone();
        nvDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        nanDao = new NanDao(nanDaoConfig, this);
        nvDao = new NvDao(nvDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Nan.class, nanDao);
        registerDao(Nv.class, nvDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        nanDaoConfig.clearIdentityScope();
        nvDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public NanDao getNanDao() {
        return nanDao;
    }

    public NvDao getNvDao() {
        return nvDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
